// Package buildimage assembles Docker build contexts for prebaked agent images.
package buildimage

import "fmt"

// GenerateDockerfile returns Dockerfile content for a prebaked agent image.
// The generated image copies the pre-staged workspace directory and touches
// the ready sentinel so the entrypoint skips the wait.
func GenerateDockerfile(baseImage string) []byte {
	const tmpl = `# Generated by: gc build-image
ARG BASE=%s
FROM ${BASE}
USER root
COPY workspace/ /workspace/
RUN chown -R gcagent:gcagent /workspace && touch /workspace/.gc-workspace-ready
USER gcagent
`
	return []byte(fmt.Sprintf(tmpl, baseImage))
}
